name: inference-pipeline

on:
  workflow_run:
    workflows: ["feature-pipeline"]
    types:
      - completed

  workflow_dispatch:

env:
    PYTHON_VERSION: 3.9
    POETRY_VERSION: 1.7.1
    POETRY_URL: https://install.python-poetry.org

jobs:

  inference_pipeline:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Poetry cache depends on OS, Python version and Poetry version.
    - name: Cache Poetry cache
      uses: actions/cache@v3

      with:
        path: ~/.cache/pypoetry
        key: poetry-cache-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.POETRY_VERSION }}
    
    # virtualenv cache should depends on OS, Python version and `poetry.lock` (and optionally workflow files).
    - name: Cache Packages
      uses: actions/cache@v3
      with:
        path: ~/.local
        key: poetry-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}
    
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install Poetry
      run: |
            (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | py - --version $env:POETRY_VERSION
            $env:PATH = $env:PATH + ";$env:USERPROFILE\.local\bin"
    
    
    - name: Install Dependencies
      run: poetry install
        
    - name: Generating new batch of predictions
      env: 
        HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        COMET_ML_API_KEY: ${{ secrets.COMET_ML_API_KEY }}
        COMET_ML_WORKSPACE: ${{ secrets.COMET_ML_WORKSPACE }}
        COMET_ML_PROJECT_NAME: ${{ secrets.COMET_ML_PROJECT_NAME }}
      run: make inference
  